# LISTA DE FRASES DO JARVIS - VERSÃO ATUALIZADA
online = [
    "SISTEMAS ACIONADOS, SENHOR. ESTOU ONLINE!",
    "REATOR ARC CARREGADO. O QUE MANDA, IGOR?",
    "JARVIS PRONTO PARA SERVIR. É SÓ CHAMAR!"
]

offline = [
    "ENTRANDO EM MODO DE REPOUSO. ATÉ MAIS!",
    "SISTEMAS DESLIGANDO. SE PRECISAR, É SÓ ME LIGAR.",
    "VOU DESCANSAR MEUS CIRCUITOS."
]

netflix_fala = [
    "PREPARANDO O CINEMA EM CASA. O QUE VAMOS VER?",
    "ABRINDO A NETFLIX. NÃO ESQUEÇA A PIPOCA!",
    "MÉTODO CINEMATOGRÁFICO ATIVADO."
]

gameplay_fala = [
    "MODO GAMER ATIVADO. BOA SORTE!",
    "ABRINDO O JOGO. MOSTRE QUEM É O CHEFE!"
]

spotify_fala = [
    "SOLTANDO O SOM. O QUE VAMOS OUVIR HOJE?",
    "SISTEMA DE ÁUDIO PRONTO. ABRINDO SPOTIFY."
]

yt_fala = [
    "ABRINDO O YOUTUBE. QUAL O VÍDEO DE HOJE?",
    "PODE DEIXAR, ESTOU CARREGANDO O YOUTUBE."
]

desligar_luz = [
    "ENTENDIDO. DEIXANDO O QUARTO NO ESCURO.",
    "LUZES APAGADAS. BOA NOITE, SENHOR."
]

acender_luz = [
    "ACENDENDO AS LUZES. JÁ PODE ABRIR OS OLHOS!",
    "CLAREANDO O AMBIENTE, SENHOR."
]